apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    app: mssql
  ports:
  - name: mssql
    port: 1433
  clusterIP: None
  selector:
    app: mssql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  serviceName: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: mssql
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        envFrom:
        - configMapRef:
            name: mssql
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
        envFrom:
        - configMapRef:
            name: mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
